title: "InnerChronicles"
email: inner.chronicles.blog@gmail.com
timezone: UTC
url: "https://www.innerchronicles.com"
permalink: "/:title/"
logo: 'assets/images/logo.png'
favicon: 'assets/images/favicon.ico'
author: InkScribe
paginate: 30
disqus: 'demowebsite'
locale: en_us
lang: en_us
feed_items: 10
feed_update_period: daily
feed_update_frequency: 1
markdown: kramdown
kramdown:
  syntax_highlighter_opts:
    disable: true
sass:
  sass_dir: _sass
  style: :compressed
ganalytics: G-YD1ECMKWFR

# Authors
authors:
  inkscribe:
    name: inkscribe
    display_name: InkScribe
    avatar: 'assets/images/sal.png'
    email: inner.chronicles.blog@gmail.com
    web: https://www.innerchronicles.com
    twitter: javascrit:void(0);
    description: "InkScribe is a passionate wordsmith and storyteller, weaving tales that explore the depths of human experiences. With a knack for blending reality and imagination, InkScribe invites readers on thought-provoking journeys that inspire introspection and ignite the imagination."

# Social
social:
  instagram: javascrit:void(0);
  facebook: javascrit:void(0);
  twitter: javascrit:void(0);

# Plugins
plugins: 
- jekyll-paginate
- jekyll-sitemap
- jekyll-feed
- jekyll-seo-tag
- jekyll-archives
