title: "InnerChronicles"
email: nishanta454@gmail.com
timezone: UTC
baseurl: "/inner-chronicles"
permalink: "/:title/"
logo: 'assets/images/logo.png'
favicon: 'assets/images/favicon.ico'
author: Nishant
paginate: 30
disqus: 'demowebsite'
locale: en_us
lang: en_us
feed_items: 10
feed_update_period: daily
feed_update_frequency: 1
markdown: kramdown
kramdown:
  syntax_highlighter_opts:
    disable: true
sass:
  sass_dir: _sass
  style: :compressed
ganalytics: UA-113961478-1

# Authors
authors:
  nishant:
    name: Nishant
    display_name: Nishant
    avatar: 'assets/images/sal.png'
    email: nishanta454@gmail.com
    web: https://www.innerchronicles.com
    twitter: https://twitter.com/wowthemesnet
    description: "A passionate storyteller, weaving words into captivating narratives that touch hearts and ignite imagination, bringing the hidden realms of life to light through the pages of InnerChronicles."

# Social
social:
  instagram: javascrit:void(0);
  facebook: javascrit:void(0);
  twitter: javascrit:void(0);

# Plugins
plugins: 
- jekyll-paginate
- jekyll-sitemap
- jekyll-feed
- jekyll-seo-tag
- jekyll-archives